### PR TITLE
Update aapt and readd origin ContentType

### PR DESCRIPTION
**Pull request by FioneraGH**
- Update aapt to 28.0.1 with 64bit, bacause after macOS 10.13.4, 32bit is limited

- "dyn.ah62d4rv4ge80c6dp" from mdls is still needed for those apk files which are not associated with other application

### CODE REVIEW

**Comment by hezi** [comment]
Thanks

**Comment by youssman** [comment]
hello,

The QuickLookAPK.qlgenerator.zip file was removed. was it wanted ?

Best regards

**Comment by FioneraGH** [comment]
@youssman Its an old version. You can assemble one by yourself.

**Comment by youssman** [comment]
Hey @FioneraGH thanks for your reply.

Actually deleting this file broke the installation process using Homebrew. This is why I'm reporting the missing file.

I don't know if you would like to give the possibility to people to install it using [Homebrew](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/quicklookapk.rb).

Best regards

**Pull request merged**
